#!/bin/bash

clear

fun_bar () {

comando[0]="$1"

comando[1]="$2"

 (

[[ -e $HOME/fim ]] && rm $HOME/fim

${comando[0]} > /dev/null 2>&1

${comando[1]} > /dev/null 2>&1

touch $HOME/fim

 ) > /dev/null 2>&1 &

 tput civis

echo -ne "   \033[1;33mPLEASE WAIT ... \033[1;37m- \033[1;33m["

while true; do

   for((i=0; i<18; i++)); do

   echo -ne "\033[1;31m#"

   sleep 0.1s

   done

   [[ -e $HOME/fim ]] && rm $HOME/fim && break

   echo -e "\033[1;33m]"

   sleep 1s

   tput cuu1

   tput dl1

   echo -ne "   \033[1;33mPLEASE WAIT ... \033[1;37m- \033[1;33m["

done

echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"

tput cnorm

}


  echo " "
  
  echo -e "\033[1;32m********************************************\033[0m"
  echo -e "         \033[1;32mอัพเดท เมนูสคริป และ ระบบต่างๆ\033[0m
  echo -e "\033[1;32m********************************************\033[0m"
  

  echo -ne "  \033[1;32m◇ WISH TO UPDATE \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read res

  if [[ "$res" = s || "$res" = S ]];then

    echo -e "  \033[1;32m◇ เริ่มต้นการอัพเดท..."

    sleep 3

    wget https://raw.githubusercontent.com/aritach/vps-new/master/Dark
    
    chmod 777 Dark
    
    ./Dark 

    clear

    echo -e "\033[1;32m◇ อัพเดท เรียบร้อย\033[0m\n"

    rm /tmp/att > /dev/null 2>&1

    echo -ne "\033[1;31m◇ ENTER \033[1;33mto return to \033[1;32mMENU!\033[0m"; read

    menu

  else

    menu

  fi

}

