#!/bin/bash

echo -e "       \033[1;31m!!##### "\033[1;336mคำเตือน "\033[1;31m#####!!\033[0m"
echo " "
echo -e "\033[1;33mรหัสผ่าน root ใช้สำหรับเข้าใช้งานเพื่อ ติดตั้ง ปรับแต่ง เซิฟเวอร์\033[0m"
echo -e "       \033[0;31mENTER NEW PASSWORD \033[1;36m
    ใส่รหัสผ่านใหม่ที่ต้องการ...\033[1;31m\033[0m"
    read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;32mเปลี่ยนรหัสผ่าน root เสร็จเรียบร้อย!\033[0m"
sleep 5s
cd
clear

